### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by ahjsrhj** [Portan/Mi-r1d#2]
有没有使用的介绍？直接clone到r1d上运行么？

**Comment by Portan** [comment]
我自己用的，所以没有什么说明，首先变成可读写状态：mount -o remount -rw /,  clone到R1d里面，编辑下/etc/shadowsocks.json里的服务器和端口，最后运行/etc/init.d/myshadowsocks。
目前我的小米路由器的UDP转发功能还不行，不知怎么回事一直是UDP处于block状态，TCP没问题。你可以试试

**Comment by ahjsrhj** [comment]
昨天刚把小米刷成了tomato,用不上啦，谢谢
